# Generated by Django 3.1.3 on 2021-01-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtest', '0004_pcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='realtest.Category'),
        ),
    ]
